import * as vscode from 'vscode';
import * as path from 'path';

export class ReadmeWizard {
  public static readonly viewType = 'zyrehub.readmeWizard';

  public static show(extensionUri: vscode.Uri) {
    const column = vscode.window.activeTextEditor
      ? vscode.window.activeTextEditor.viewColumn
      : undefined;

    const panel = vscode.window.createWebviewPanel(
      ReadmeWizard.viewType,
      'ZyreHub: README Wizard',
      column || vscode.ViewColumn.One,
      {
        enableScripts: true,
        localResourceRoots: [
          vscode.Uri.joinPath(extensionUri, 'media'),
          vscode.Uri.joinPath(extensionUri, 'Assets')
        ]
      }
    );

    panel.webview.html = this.getHtmlForWebview(panel.webview, extensionUri);

    panel.webview.onDidReceiveMessage(
      async message => {
        switch (message.command) {
          case 'generate':
            await this.generateReadme(message.data);
            panel.dispose();
            return;
        }
      },
      undefined
    );
  }

  private static async generateReadme(data: any) {
    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (!workspaceFolders) return;

    const projectPath = workspaceFolders[0].uri.fsPath;
    const readmePath = path.join(projectPath, 'README.md');

    const content = `# ${data.name}
> ${data.description}

## Features
${data.features.split('\n').map((f: string) => `- ${f}`).join('\n')}

## Installation
\`\`\`bash
${data.installation}
\`\`\`

## Usage
${data.usage}

---
*Generated by [ZyreHub](https://github.com/SnoW-099/zyrehub.git)*
`;

    const uri = vscode.Uri.file(readmePath);
    await vscode.workspace.fs.writeFile(uri, Buffer.from(content, 'utf8'));
    vscode.window.showInformationMessage('ZyreHub: README.md generated successfully!');
    
    const doc = await vscode.workspace.openTextDocument(uri);
    await vscode.window.showTextDocument(doc);
  }

  private static getHtmlForWebview(webview: vscode.Webview, extensionUri: vscode.Uri) {
    const logoPath = webview.asWebviewUri(vscode.Uri.joinPath(extensionUri, 'Assets', 'logo.png'));

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>README Wizard</title>
    <style>
        body { font-family: sans-serif; padding: 20px; color: var(--vscode-foreground); background-color: var(--vscode-editor-background); }
        .header { display: flex; align-items: center; gap: 15px; margin-bottom: 20px; }
        .logo { width: 50px; height: 50px; object-fit: contain; }
        .form-group { margin-bottom: 15px; }
        label { display: block; margin-bottom: 5px; font-weight: bold; }
        input, textarea { width: 100%; padding: 8px; border: 1px solid var(--vscode-input-border); background: var(--vscode-input-background); color: var(--vscode-input-foreground); box-sizing: border-box; }
        button { background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: none; padding: 10px 20px; cursor: pointer; font-weight: bold; }
        button:hover { background: var(--vscode-button-hoverBackground); }
    </style>
</head>
<body>
    <div class="header">
        <img src="${logoPath}" class="logo" alt="ZyreHub Logo">
        <h1>ZyreHub README Wizard</h1>
    </div>
    <div class="form-group">
        <label>Project Name</label>
        <input type="text" id="name" placeholder="My Awesome Project">
    </div>
    <div class="form-group">
        <label>Short Description</label>
        <textarea id="description" rows="2"></textarea>
    </div>
    <div class="form-group">
        <label>Features (one per line)</label>
        <textarea id="features" rows="4"></textarea>
    </div>
    <div class="form-group">
        <label>Installation Commands</label>
        <input type="text" id="installation" value="npm install">
    </div>
    <div class="form-group">
        <label>Usage Instructions</label>
        <textarea id="usage" rows="3"></textarea>
    </div>
    <button id="generate">Generate README.md</button>

    <script>
        const vscode = acquireVsCodeApi();
        document.getElementById('generate').addEventListener('click', () => {
            const data = {
                name: document.getElementById('name').value,
                description: document.getElementById('description').value,
                features: document.getElementById('features').value,
                installation: document.getElementById('installation').value,
                usage: document.getElementById('usage').value
            };
            vscode.postMessage({ command: 'generate', data });
        });
    </script>
</body>
</html>`;
  }
}
